name: debian-multiarch-triplet-provider-launch
title: X_DEBIAN_MULTIARCH_TRIPLET Provider
version: git
summary: Generate X_DEBIAN_MULTIARCH_TRIPLET for good
description: |
  Refer the following forum topic for more info on using this stage snap:

      The debian-multiarch-triplet-provider-launch Stage Snap - doc - snapcraft.io
      https://forum.snapcraft.io/t/the-debian-multiarch-triplet-provider-launch-stage-snap/11738

# build on least busy architecture
architectures:
- build-on: ppc64el
  run-on: all
base: core
grade: stable
confinement: strict

parts:
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/
